### ISSUE TITLE
(Not an issue) questions regarding modifications to the repo

### ISSUE THREAD

**Issue by kskim7** [kushwavez/lenovo-x1c6-clover-efi#6]
Hi bro, it's been a while, hope you're doing good.
Still remember me? I've been away from my X1C6 for more than a year and now I got another Thinkpad - X270.
I tried almost all efi's available here at GitHub for my x270, nothing really worked.
But then, your Eli's for X1C6 did a magic! 
Your EFI did wonderful job at installation, and it also boots up well after the installation.

But the thing is, my CPU is 7th gen Intel - which is, i5-7200U.
It shares the same architecture - Kabylake. It also has UHD620. 
I guess that's why your EFI also worked with mine.

But for now, the bluetooth doesn't seem to work.
The thing is.. my memory of how to hackintosh is almost all gone since I was away from hackintosh for more than a year..
Could you recommend me what I must do to properly implement your EFI's to my system?
Maybe I should start with DSDT and stuff??

Any help would be very much appreciated!!
Thanks!!

**Comment by kushwavez** [comment]
Hi
Sorry for the very delayed response. I am not very active in the hackintoshing scene anymore

I know you comment is 1 year old, you may already solved this.

I think the issue is with the USB Port mapping, you may need to re-do that for the X270. 
I have used Hackintool's USB Port mapping tool. Click the info "I" button and it'll guide you trough the whole process.

You will be presented by a USBPorts.kext that you need to place to CLOVER/kexts/Other 

After that the bt should work (assuming it's replaced to BCM94360). 

If it is intel then you need BluetoolFixup and IntelBT kexts from 
https://github.com/OpenIntelWireless/IntelBluetoothFirmware

**Comment by kskim7** [comment]
Wow, after all these years..! thanks for the reply!!

Thanks to other repos, I've successfully installed macOS Monterey to X270,
and now I'm using Carbon gen 6 again, on Sonoma this time.

Thank you very much for a thorough explanations about the USB mapping,
your kindness will surely be paid in your real life, I wish =)

Good luck in everything!!!
